repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
      exclude: docs
-   repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
    - id: isort
      args: ["--profile", "black"]
      exclude: docs
-   repo: local
    hooks:
    - id: test
      name: Check test pass/fail
      types: [python]
      entry: python -m unittest/
      language: system
      pass_filenames: false
      always_run: true
