learning_rate: [0.1, 0.3, 0.5]  # Learning rate
max_depth: [5, 8, 10]           # Maximum depth of a tree
n_estimators: [10, 50, 100]     # Number of estimators
num_parallel_tree: [1, 2]       # Number of trees
gamma: [0, 0.5]                 # Minimum split loss
lambda: [0.5, 1]                # Regularization term
scale_pos_weight: [0.5, 1]      # Balance between positive and negative weights
min_child_weight: [0.5, 1]      # Minimum sum of weights of all observations in a child
objective: ["binary:logistic"]  # Loss function
tree_method: ["hist"]           # Histogram tree grow method
verbosity: [0]                  # Verbosity of printing messages
