learning_rate: 0.12           # Learning rate eta
max_depth: 10                 # Naxunyn depth of a tree
n_estimators: 10              # Number of trees
gamma: 0                      # Minimum split loss
lambda: 1                     # Regularization term
scale_pos_weight: 1           # Balance between positive and negative weights
min_child_weight: 1           # Minimum sum of weights of all observations in a child
objective: "binary:logistic"  # Loss function
tree_method: "hist"           # Histogram tree grow method
verbosity: 0                  # Verbosity of printing messages
